### ISSUE TITLE
No suitable hoster found

### ISSUE THREAD

**Issue by sixteeN11** [zapp-brannigan/own-pyload-plugins#1]
hi, ich bekomme bei jedem download, auch wenn ich ihn manuell eintrage den o.g. fehler.
ist das bekannt?

grüße

**Comment by zapp-brannigan** [comment]
Ich vermute du hast den Hoster falsch geschrieben oder es kein Hoster verfügbar den du in die Whitelist eingetragen hast. Ein Debuglog wäre hilfreich.

**Comment by zapp-brannigan** [comment]
Hat sich wohl erledigt.
