### ISSUE TITLE
MovieblogOrg - 'MovieblogOrg' object has no attribute 'links'

### ISSUE THREAD

**Issue by macross5** [zapp-brannigan/own-pyload-plugins#2]
Im unable to handle the crypter. I checked the pattern and they are up to date. Cause of some reason hes unable to add links.
As hoster i gave: UploadedTo,UploadedNet

Some help or still a hint would be nice.

**Comment by macross5** [comment]
P.S.: Englisch kannst du wahrscheinlich auch, aber dennoch der Hinweis, dass ich Deutsch ebenso verstehe.

**Comment by zapp-brannigan** [comment]
Danke fürs Melden, ich kümmer mich drum.

**Comment by zapp-brannigan** [comment]
Probier mal Version 0.09. Sollte wieder funktionieren.

**Comment by macross5** [comment]
Danke für die schnelle Hilfe!
Bei manchen kommt sowas, obwohl Links auf der Website vorhanden sind:

> ERROR	Decrypting failed: X | Parse error: No links found | Plugin may be out of date

(Name wurde durch X ersetzt)

Bei anderen schafft er es zu encrpyten: http://filecrypt.cc/Container/X.html. Darauffolgend kommt der Fehler bei FilecryptCc:

> ERROR	Decrypting failed: http://filecrypt.cc/Container/X.html | 'NoneType' object has no attribute 'group'

**Comment by zapp-brannigan** [comment]
Poste mal den Link der sich nicht entschlüsseln lässt ("X" aus deinem Kommentar).
Am Filecrypt-Problem arbeite ich auch schon, nur gedult ;)

**Comment by macross5** [comment]
File info: {'status': 2, 'url': u'http://www.movie-blog.org/2015/07/28/thor-2011-german-1080p-bluray-x264-moviestars', 'size': 0, 'name': u'Thor.2011.German.1080p.BluRay.x264-MOViESTARS', 'pattern': {'N': u'Thor.2011.German.1080p.BluRay.x264-MOViESTARS'}}

**Comment by zapp-brannigan** [comment]
Ist behoben, bitte nochmal testen.

**Comment by macross5** [comment]
Dein Crypter funktioniert nun perfekt :) Danke sehr!
Hier noch eine kleine Info, die dir vllt. bei linkcrypt helffen könnte :+1: 

> Decrypting failed: http://linkcrypt.ws/dir/X | 'bool' object has no attribute 'decrypt'

**Comment by zapp-brannigan** [comment]
Gerne ;) Ich mach dann mal zu.

**Comment by macross5** [comment]
Hi! Gibt es schon was neues bezüglich des Filecrypt-Problems?

> DEBUG	CRYPTER FilecryptCc[728]: Previous wantReconnect: False
INFO	CRYPTER FilecryptCc[728]: RECONNECT disabled
DEBUG	CRYPTER FilecryptCc[728]: Previous waitUntil: 1440521254.983624
INFO	CRYPTER FilecryptCc[728]: WAIT 1 seconds
ERROR	CAPTCHA FilecryptCc[728]: Captcha | Invalid captcha
DEBUG	CAPTCHA FilecryptCc[728]: Captcha | LOAD URL https://www.filecrypt.cc/../captcha/captcha.php?namespace=container | cookies=False | get={} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
DEBUG	CRYPTER FilecryptCc[728]: Captcha-URL: ../captcha/captcha.php?namespace=container
DEBUG	CRYPTER FilecryptCc[728]: LOAD URL https://www.filecrypt.cc/Container/2D3E63F695.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG	CRYPTER FilecryptCc[728]: PROCESS URL https://www.filecrypt.cc/Container/2D3E63F695.html | PLUGIN VERSION 0.19
DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
INFO	Decrypting starts: https://www.filecrypt.cc/Container/2D3E63F695.html
INFO	Retrying https://www.filecrypt.cc/Container/2D3E63F695.html

**Comment by zapp-brannigan** [comment]
Leider nicht. Mit der aktuellen pyloadversion funktionieren bei filecrypt nur solvemedia captchas. Keine ahnung woran das liegt :(

Am 25. August 2015 18:53:32 MESZ, schrieb macross5 <notifications@github.com>:
>Hi! Gibt es schon was neues bezüglich des Filecrypt-Problems?
>
>> DEBUG	CRYPTER FilecryptCc[728]: Previous wantReconnect: False
>INFO	CRYPTER FilecryptCc[728]: RECONNECT disabled
>DEBUG	CRYPTER FilecryptCc[728]: Previous waitUntil: 1440521254.983624
>INFO	CRYPTER FilecryptCc[728]: WAIT 1 seconds
>ERROR	CAPTCHA FilecryptCc[728]: Captcha | Invalid captcha
>DEBUG	CAPTCHA FilecryptCc[728]: Captcha | LOAD URL
>https://www.filecrypt.cc/../captcha/captcha.php?namespace=container |
>cookies=False | get={} | req=None | decode=False | multipart=False |
>post={} | ref=False | just_header=False
>DEBUG	CRYPTER FilecryptCc[728]: Captcha-URL:
>../captcha/captcha.php?namespace=container
>DEBUG	CRYPTER FilecryptCc[728]: LOAD URL
>https://www.filecrypt.cc/Container/2D3E63F695.html | cookies=True |
>get={} | req=None | decode=True | multipart=False | post={} | ref=True
>| just_header=False
>DEBUG	CRYPTER FilecryptCc[728]: PROCESS URL
>https://www.filecrypt.cc/Container/2D3E63F695.html | PLUGIN VERSION
>0.19
>DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0
>(Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
>INFO	Decrypting starts:
>https://www.filecrypt.cc/Container/2D3E63F695.html
>INFO	Retrying https://www.filecrypt.cc/Container/2D3E63F695.html
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zapp-brannigan/own-pyload-plugins/issues/2#issuecomment-134668892

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by macross5** [comment]
Hast du vllt eine ältere wo alles läuft? Wenn ja, könntest du die irgendwo hochladen?
Vor zwei Monaten lief alles super ohne Probleme und nun wieder alles blöd :( Hätte mir da mal ein Backup machen sollen -.-

**Comment by zapp-brannigan** [comment]
Probier mal die Version vom 1. Juni, vielleicht gehts da noch:
https://github.com/pyload/pyload/archive/ee383fe3d45aded7be86d3b06e256c94829614e1.zip
Bevor du zum ersten mal startest solltest du allerdings die Updatemanager.py finden und löschen ;)
