### ISSUE TITLE
SerienjunkiesOrg Crypter - 'SerienjunkiesOrg' object has no attribute 'core'

### ISSUE THREAD

**Issue by macross5** [zapp-brannigan/own-pyload-plugins#4]
Hi, ich mal wieder. Benutze die SJ Hook von Gutz-Pilz und die aktuelle Version deines Serienjunkies Crypter. Ebenso (noch) die aktuellste Version von Pyload.
Weiß jetzt nicht, ob der Fehler auf der Seite des Crypters oder der Seite der Hook liegt.
Danke schon einmal für deinen super Support!

> ERROR	Decrypting failed: http://download.serienjunkies.org/f-0c7ff031a3db0e24/ul_tvp-shield-s02e08-720p.html | 'SerienjunkiesOrg' object has no attribute 'core'
INFO	CAPTCHA SerienjunkiesOrg[1029]: Captcha | Correct captcha
DEBUG	CONTAINER SerienjunkiesOrg[1029]: LOAD URL http://download.serienjunkies.org/f-0c7ff031a3db0e24/ul_tvp-shield-s02e08-720p.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={'action': 'Download', 's': u'469d473a180f31dc5c0e1dbc343c025d', 'c': '4RW'} | ref=True | just_header=False
INFO	CAPTCHA SerienjunkiesOrg[1029]: Captcha | Captcha result: 4RW
DEBUG	CAPTCHA SerienjunkiesOrg[1029]: Captcha | LOAD URL http://download.serienjunkies.org/secure/66dd9ed1d9229c4adc51925c6a89385f.png | cookies=False | get={} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
DEBUG	CONTAINER SerienjunkiesOrg[1029]: PROCESS URL http://download.serienjunkies.org/f-0c7ff031a3db0e24/ul_tvp-shield-s02e08-720p.html | PLUGIN VERSION 0.40
DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
INFO	Decrypting starts: http://download.serienjunkies.org/f-0c7ff031a3db0e24/ul_tvp-shield-s02e08-720p.html

**Comment by zapp-brannigan** [comment]
Schau bitte mal im forum nach dem crypter, kann sein dass "meine" version hier nicht richtig funktioniert.

Am 26. August 2015 20:04:02 MESZ, schrieb macross5 <notifications@github.com>:
>Hi, ich mal wieder. Benutze die SJ Hook von Gutz-Pilz und die aktuelle
>Version deines Serienjunkies Crypter. Ebenso (noch) die aktuellste
>Version von Pyload.
>Weiß jetzt nicht, ob der Fehler auf der Seite des Crypters oder der
>Seite der Hook liegt.
>Danke schon einmal für deinen super Support!
>
>> ERROR	Decrypting failed:
>http://download.serienjunkies.org/f-0c7ff031a3db0e24/ul_tvp-shield-s02e08-720p.html
>| 'SerienjunkiesOrg' object has no attribute 'core'
>INFO	CAPTCHA SerienjunkiesOrg[1029]: Captcha | Correct captcha
>DEBUG	CONTAINER SerienjunkiesOrg[1029]: LOAD URL
>http://download.serienjunkies.org/f-0c7ff031a3db0e24/ul_tvp-shield-s02e08-720p.html
>| cookies=True | get={} | req=None | decode=True | multipart=False |
>post={'action': 'Download', 's': u'469d473a180f31dc5c0e1dbc343c025d',
>'c': '4RW'} | ref=True | just_header=False
>INFO	CAPTCHA SerienjunkiesOrg[1029]: Captcha | Captcha result: 4RW
>DEBUG	CAPTCHA SerienjunkiesOrg[1029]: Captcha | LOAD URL
>http://download.serienjunkies.org/secure/66dd9ed1d9229c4adc51925c6a89385f.png
>| cookies=False | get={} | req=None | decode=False | multipart=False |
>post={} | ref=False | just_header=False
>DEBUG	CONTAINER SerienjunkiesOrg[1029]: PROCESS URL
>http://download.serienjunkies.org/f-0c7ff031a3db0e24/ul_tvp-shield-s02e08-720p.html
>| PLUGIN VERSION 0.40
>DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0
>(Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
>INFO	Decrypting starts:
>http://download.serienjunkies.org/f-0c7ff031a3db0e24/ul_tvp-shield-s02e08-720p.html
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zapp-brannigan/own-pyload-plugins/issues/4

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by macross5** [comment]
Deine ist etwas veraltet, stimmt. Danke für den Hinweis. 
Hier die aktuelle: http://forum.pyload.org/viewtopic.php?f=7&t=3680&start=50
Damit funktioniert es nun :)
