### ISSUE TITLE
Traktfetcher.

### ISSUE THREAD

**Issue by Gutz-Pilz** [zapp-brannigan/own-pyload-plugins#5]
Hi.
Hättest du lust, mit mir meinen Traktfetcher plugin zu erweitern und auszubauen ?
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/TraktFetcher.py
Diese alte version liest jeden eintrag per beautifulsoup aus.

hier habe ich unabhängig von pyload schonmal angefangen mit hilfe der trakt api eine traktliste auszulesen und auf hdarea zu suchen.
https://gist.github.com/Gutz-Pilz/e78ac8a10bd8e9699454

meine Vorstellung wäre noch movieblog mit in die suche aufzunehmen

**Comment by zapp-brannigan** [comment]
Weiter via PN im Forum.
