### ISSUE TITLE
Errors with new Event handlers

### ISSUE THREAD

**Issue by rix1337** [zapp-brannigan/own-pyload-plugins#6]
Hi. Thanks for the great work,

with the Holiday Updates the MB plugin stopped working. Any luck looking into the issue (likely the periodical event handling)...?

**Comment by zapp-brannigan** [comment]
Hook oder Crypter?

**Comment by rix1337** [comment]
Wohl beide:

```06.01.2016 14:32:35 ERROR Error importing MovieblogOrg: cannot import name parse_fileInfo
...
06.01.2016 14:32:35 ERROR Error executing hooks: 'MovieblogFeed' object has no attribute 'start_periodical'```

**Comment by zapp-brannigan** [comment]
Teste bitte mal die beiden neuen Versionen.

**Comment by rix1337** [comment]
Hey, danke fürs fixen.

Sieht so aus als ginge es problemlos weiter (keine Errormeldungen mehr).
